### PR TITLE
game: Retain old 'BG_PlayerTouchesItem' for CTF flags

### LINKED ISSUE #2827: New Entity pickup/touching regression
Reported on Discord by `adr` [link](https://discord.com/channels/260750790203932672/346956915814957067/1290058964494581912) - on latest snapshot with the new pickup/touch, picking up objectives on standard maps doesn't work as expected anymore.

https://github.com/user-attachments/assets/1538b44b-867b-4f0e-bff2-082aebb43193

### PR DESCRIPTION
**Pull request by Vorschreibung**
The newly introduced 'BG_PlayerTouchesItem' is working fine and dandy for medi/ammo packs, however it also affected mission objectives (CTF flags) in existing maps and ways that messed with player expectations.

This commit readds the old 'BG_PlayerTouchesItem' logic in 'BG_PlayerTouchesItemOld' and uses it whenever we are to intersect with CTF flag entities.

Fixes https://github.com/etlegacy/etlegacy/issues/2827

### CODE REVIEW

File: src/game/bg_public.h [hunk 1]
```diff
@@ -2128,7 +2128,8 @@ void BG_AddPredictableEventToPlayerstate(int newEvent, int eventParm, playerStat
 
 void BG_PlayerStateToEntityState(playerState_t *ps, entityState_t *s, int time, qboolean snap);
 
-qboolean BG_PlayerTouchesItem(playerState_t *ps, entityState_t *item, int atTime);
+qboolean BG_PlayerTouchesItemNew(playerState_t *ps, entityState_t *item, int atTime);
+qboolean BG_PlayerTouchesItemOld(playerState_t *ps, entityState_t *item, int atTime);
```
Comment (Aranud) [inline src/game/bg_public.h]: Perhaps a more generic / specific name would be welcome. 
Such as BG_PlayerTouchesItemSquare/CylinderBBox

File: src/game/g_local.h [hunk 2]
```diff
@@ -307,6 +307,7 @@ struct gentity_s
 	vec3_t instantVelocity;         ///< per entity instantaneous velocity, set per frame
 
 	const char *classname;          ///< set in QuakeEd
+	long classnameHash;             ///< derived from classname
```
Comment (Aranud) [inline src/game/g_local.h]: Could it be separate in another PR ?

**Review by Aranud — CHANGES_REQUESTED** [review]

File: src/game/bg_public.h (hunk 1 above)
Comment (Aciz) [reply src/game/bg_public.h]: I'd propose `BG_PlayerTouchesItem` & `BG_PlayerTouchesObjective`, since the other is used exclusively for objectives, and the other is for all other items

**Comment by Vorschreibung** [comment]
Resolved all review input. Ready to re-review/merge.

**Comment by ensiform** [comment]
Instead of classname matching you can compare item giType with IT_TEAM which is only true for PW_REDFLAG / PW_BLUEFLAG (objectives) aka the 2 team'd flags

**Comment by Vorschreibung** [comment]
> Instead of classname matching you can compare item giType with IT_TEAM which is only true for PW_REDFLAG / PW_BLUEFLAG (objectives) aka the 2 team'd flags

~~that's on `gitem_t` tho - `hit` is `gentity_t`~~ nvm. didn't see `hit->item`

**Comment by ensiform** [comment]
See 

```c
gentity_s::item
```

Which is valid pointer if its an item.

**Comment by Vorschreibung** [comment]
> See
> 
> ```c
> gentity_s::item
> ```
> 
> Which is valid pointer if its an item.

Thanks! Exactly what we needed.
